window.STARHORIZON_DEFAULTS = {
  site: {
    brandName: "星澔文創",
    englishName: "STARHORIZON CREATIVE",
    tagline: "影音製作工作室",
    email: "hello@starhorizon.tw",
    phone: "尚未設定",
    line: "尚未設定",
    instagram: "",
    youtube: "",
    gaId: "",
    metaPixelId: "",
    seoTitle: "星澔文創｜品牌影片、訪談、Podcast 與社群短影音製作",
    seoDescription:
      "星澔文創提供品牌形象影片、人物訪談、Podcast 影像、短影音切片、活動紀錄與後期剪輯包裝，協助品牌用影像建立信任並促成詢價。",
  },
  home: {
    eyebrow: "Video Production / Brand Film / Social Cuts",
    title: "讓品牌被看見，也被記住。",
    subtitle:
      "星澔文創協助企業從企劃、拍攝、剪輯到後製完整完成影像內容，讓作品不只是漂亮，而是能說清楚價值、建立信任、推動下一步合作。",
    primaryCtaText: "觀看作品",
    primaryCtaLink: "works.html",
    secondaryCtaText: "取得報價",
    secondaryCtaLink: "quote.html",
    showreelLabel: "SHOWREEL 2026",
    showreelUrl: "",
  },
  about: {
    title: "我們相信，好的影像不是單純記錄，而是幫品牌完成溝通。",
    body:
      "星澔文創是一間以品牌敘事與商業溝通為核心的影音製作工作室。我們擅長把企業理念、人物觀點、產品特色與活動現場轉化成可被理解、可被分享、可被使用的影像資產。",
    philosophy:
      "每一支影片都應該先回答三件事：誰要看、看完要理解什麼、下一步要做什麼。從這個基礎出發，我們規劃腳本、拍攝節奏、剪輯版本與社群延伸素材。",
    serviceArea: "台灣全區，可依專案需求安排外縣市拍攝。",
    team: [
      {
        name: "製作企劃",
        role: "需求訪談、腳本架構、拍攝規劃",
      },
      {
        name: "影像團隊",
        role: "攝影、燈光、收音、現場執行",
      },
      {
        name: "後製團隊",
        role: "剪輯、調色、字幕、音訊與社群版本輸出",
      },
    ],
    clients: ["品牌形象", "教育課程", "Podcast 節目", "活動紀錄"],
  },
  works: [
    {
      id: "brand-film",
      title: "品牌形象影片",
      category: "品牌形象",
      client: "精選案例",
      year: "2026",
      coverClass: "g1",
      videoUrl: "",
      summary: "用 90 秒說清楚品牌定位、服務特色與可信任的第一印象。",
      need: "客戶需要一支可用於官網首頁、簡報開場與社群投放的品牌影片。",
      production: "企劃訪談、腳本撰寫、半日拍攝、剪輯、調色、字幕與封面。",
      delivery: "橫式正片 1 支、直式短影音 3 支、封面圖 2 張。",
      featured: true,
      status: "published",
      sort: 1,
    },
    {
      id: "interview",
      title: "人物訪談影片",
      category: "人物訪談",
      client: "精選案例",
      year: "2026",
      coverClass: "g2",
      videoUrl: "",
      summary: "把創辦人理念、專家觀點與品牌故事整理成自然有溫度的內容。",
      need: "客戶希望透過人物訪談建立專業度，並剪出可分發的短版素材。",
      production: "訪綱設計、雙機拍攝、收音、剪輯、字幕與社群切片。",
      delivery: "訪談正片 1 支、精華短片 5 支、字幕版輸出。",
      featured: true,
      status: "published",
      sort: 2,
    },
    {
      id: "podcast",
      title: "Podcast 影像節目",
      category: "Podcast",
      client: "精選案例",
      year: "2026",
      coverClass: "g3",
      videoUrl: "",
      summary: "打造節目視覺，延伸成 YouTube 長片與社群短片。",
      need: "客戶已經有音訊節目，希望升級成可觀看的影像內容。",
      production: "多機位錄影、聲音同步、節目剪輯、片頭片尾與短影音拆剪。",
      delivery: "YouTube 版 1 支、短影音 6 支、節目封面 1 張。",
      featured: true,
      status: "published",
      sort: 3,
    },
    {
      id: "event-recap",
      title: "活動紀錄精華",
      category: "活動紀錄",
      client: "精選案例",
      year: "2026",
      coverClass: "g4",
      videoUrl: "",
      summary: "保留現場氛圍，剪出可宣傳、可回顧的活動精華。",
      need: "客戶需要在活動後快速產出回顧影片與社群素材。",
      production: "活動拍攝、重點訪談、B-roll、精華剪輯、音樂與字幕。",
      delivery: "活動精華 1 支、短版花絮 3 支、照片精選。",
      featured: true,
      status: "published",
      sort: 4,
    },
  ],
  services: [
    {
      id: "brand-film",
      title: "品牌形象影片",
      summary: "企業簡介、品牌故事、形象廣告與官網主視覺影片。",
      target: "適合想建立第一印象、提升專業感與信任感的企業。",
      deliverables: "腳本、拍攝、剪輯、調色、字幕、橫式與直式版本。",
      sort: 1,
      status: "published",
    },
    {
      id: "interview",
      title: "人物訪談影片",
      summary: "創辦人、專家、醫師、老師、團隊故事與品牌理念訪談。",
      target: "適合需要傳遞觀點、專業知識與品牌溫度的團隊。",
      deliverables: "訪綱、拍攝、訪談正片、精華短片、字幕版。",
      sort: 2,
      status: "published",
    },
    {
      id: "podcast",
      title: "Podcast / 節目製作",
      summary: "錄影規劃、拍攝、聲音同步、節目剪輯、片頭片尾與短影音切片。",
      target: "適合想把音訊內容延伸到 YouTube 與社群平台的節目。",
      deliverables: "節目長片、短影音切片、封面、字幕與多比例輸出。",
      sort: 3,
      status: "published",
    },
    {
      id: "social-cuts",
      title: "短影音切片",
      summary: "從長影片整理重點，製作直式短影音、字幕與封面。",
      target: "適合需要穩定經營 Instagram、YouTube Shorts、TikTok 的品牌。",
      deliverables: "直式短片、字幕、標題字卡、封面圖。",
      sort: 4,
      status: "published",
    },
    {
      id: "event",
      title: "活動紀錄",
      summary: "論壇、記者會、展覽、品牌活動與課程精華紀錄。",
      target: "適合需要保留現場內容並做後續宣傳的活動。",
      deliverables: "活動精華、花絮短片、照片或指定格式素材。",
      sort: 5,
      status: "published",
    },
    {
      id: "post-production",
      title: "後期剪輯與包裝",
      summary: "剪輯、調色、字幕、音效、動態字卡與社群版本輸出。",
      target: "適合已有素材，但需要整理成專業影片的品牌。",
      deliverables: "剪輯成片、字幕、調色、音訊整理與多平台輸出。",
      sort: 6,
      status: "published",
    },
  ],
  process: [
    {
      title: "需求諮詢",
      body: "確認影片目的、平台、支數、預算、時程與參考風格。",
      sort: 1,
    },
    {
      title: "初步報價",
      body: "依需求提供報價方向、製作範圍與建議執行方式。",
      sort: 2,
    },
    {
      title: "企劃腳本",
      body: "整理訪談方向、影片架構、拍攝風格與分鏡概念。",
      sort: 3,
    },
    {
      title: "拍攝規劃",
      body: "安排場地、時程、器材、人員與拍攝細節。",
      sort: 4,
    },
    {
      title: "現場拍攝",
      body: "執行攝影、燈光、收音、導演引導與素材管理。",
      sort: 5,
    },
    {
      title: "剪輯後製",
      body: "剪輯、調色、字幕、音樂、動態包裝與版本輸出。",
      sort: 6,
    },
    {
      title: "修改確認",
      body: "依雙方約定修改次數進行調整，確認最終內容。",
      sort: 7,
    },
    {
      title: "完成交付",
      body: "交付橫式、直式、社群版或指定格式檔案。",
      sort: 8,
    },
  ],
};
