window.STARHORIZON_DEFAULTS = {
  site: {
    brandName: "星澔文創",
    englishName: "STARHORIZON CREATIVE",
    tagline: "影音製作工作室",
    email: "hello@starhorizon.tw",
    phone: "",
    line: "",
    instagram: "",
    youtube: "",
    gaId: "",
    googleSiteVerification: "",
    metaPixelId: "",
    seoTitle: "星澔文創｜品牌影片、訪談、Podcast 與社群短影音製作",
    seoDescription:
      "星澔文創提供品牌形象影片、人物訪談、Podcast 影像、短影音切片、活動紀錄與後期剪輯包裝，協助品牌用影像建立信任並促成詢價。",
    logoLetter: "S",
    logoImageUrl: "",
    logoImageAlt: "星澔文創 Logo",
    navHome: "首頁",
    navWorks: "作品案例",
    navNews: "最新消息",
    navServices: "服務項目",
    navProcess: "製作流程",
    navAbout: "關於我們",
    navQuote: "詢價",
    topCtaText: "取得報價",
    topCtaLink: "quote.html",
    footerText: "Brand Film / Interview / Podcast / Social Cuts",
    footerCtaText: "後台登入",
    footerCtaLink: "admin.html",
  },
  inquiryForm: {
    turnstileEnabled: false,
    turnstileSiteKey: "",
    turnstileErrorMessage: "請先完成真人驗證。",
    captchaEnabled: true,
    captchaQuestion: "請輸入 6 + 3 的答案",
    captchaAnswer: "9",
    fields: [
      { id: "name", label: "姓名", type: "text", required: true, placeholder: "", options: [], sort: 1, status: "published" },
      { id: "phone", label: "聯絡電話", type: "tel", required: true, placeholder: "", options: [], sort: 2, status: "published" },
      { id: "email", label: "mail", type: "email", required: true, placeholder: "", options: [], sort: 3, status: "published" },
      { id: "company", label: "公司名稱 / 統一編號", type: "text", required: false, placeholder: "", options: [], sort: 4, status: "published" },
      { id: "budget", label: "製作預算", type: "text", required: false, placeholder: "", options: [], sort: 5, status: "published" },
      {
        id: "needs",
        label: "需求內容",
        type: "checkbox",
        required: true,
        placeholder: "",
        options: ["企業形象", "影片商業", "產品拍攝", "活動紀錄", "平面攝影", "行銷短影音", "品牌策略顧問"],
        sort: 6,
        status: "published",
      },
      { id: "message", label: "補充需求", type: "textarea", required: false, placeholder: "請描述影片用途、參考風格、預計平台、目前素材狀況等。", options: [], sort: 7, status: "published" },
    ],
    videoTypeOptions: [
      "品牌形象影片",
      "人物訪談影片",
      "Podcast / 節目製作",
      "短影音切片",
      "活動紀錄",
      "產品 / 服務介紹影片",
      "後期剪輯與包裝",
    ],
    shootingOptions: ["尚未確定", "是", "否，已有素材"],
    budgetOptions: ["尚未確定", "3–6 萬", "6–10 萬", "10–20 萬", "20–30 萬", "30 萬以上"],
  },
  home: {
    eyebrow: "Video Production / Brand Film / Social Cuts",
    title: "讓品牌被看見，也被記住。",
    subtitle:
      "星澔文創協助企業從企劃、拍攝、剪輯到後製完整完成影像內容，讓作品不只是漂亮，而是能說清楚價值、建立信任、推動下一步合作。",
    primaryCtaText: "觀看作品",
    primaryCtaLink: "works.html",
    secondaryCtaText: "取得報價",
    secondaryCtaLink: "quote.html",
    showreelLabel: "SHOWREEL 2026",
    showreelUrl: "",
    showreelWorkId: "",
    showreelBottom: ["Commercial", "Interview", "Shorts"],
    tickerItems: ["BRAND FILM", "INTERVIEW", "PODCAST", "EVENT RECAP", "SOCIAL CUTS", "POST PRODUCTION"],
    partnersEyebrow: "Partners",
    partnersTitle: "合作夥伴",
    partnersDescription: "與不同領域的品牌並肩，把每一次溝通轉化成有影響力的影像。",
    partnerMarqueeDuration: 34,
    worksEyebrow: "Selected Works",
    worksTitle: "精選作品",
    worksDescription: "用案例方式呈現需求、製作內容與交付項目，不只是放影片縮圖。",
    servicesEyebrow: "Services",
    servicesTitle: "影音製作服務",
    servicesDescription: "以客戶能理解的解決方案呈現，而不只是列出攝影、剪輯、後製。",
    extendedEyebrow: "Extended Services",
    extendedTitle: "數位延伸服務",
    extendedDescription: "以網站與搜尋優化延伸影像內容的效益，讓品牌被看見之後，也更容易被找到。",
    processEyebrow: "Workflow",
    processTitle: "合作流程",
    processDescription: "降低客戶不確定感，清楚知道每個階段要準備什麼。",
    ctaEyebrow: "Start A Project",
    ctaTitle: "想把品牌故事拍成更有質感的影片嗎？",
    ctaBody: "告訴我們你想製作的內容、用途與時程，我們會協助你整理適合的影片形式與製作方案。",
    ctaText: "填寫詢價表單",
    ctaLink: "quote.html",
  },
  pages: {
    worksEyebrow: "Works / Case Studies",
    worksTitle: "不只展示影片，也說清楚每個專案解決了什麼問題。",
    worksLead: "作品案例會呈現客戶需求、製作內容與最終交付，讓客戶理解星澔文創的規劃與執行能力。",
    newsEyebrow: "News / Journal",
    newsTitle: "最新消息與影音行銷觀點。",
    newsLead: "分享影片製作、品牌溝通、SEO 與內容經營的實用文章，讓客戶更理解每一次合作能解決什麼問題。",
    servicesEyebrow: "Services",
    servicesTitle: "以解決方案規劃影像，而不是只賣拍攝與剪輯。",
    servicesLead: "每個服務都對應不同的商業情境：建立品牌、傳遞專業、經營社群、紀錄活動或整理既有素材。",
    processEyebrow: "Workflow",
    processTitle: "每個階段都清楚，拍攝才不會變成猜測。",
    processLead: "從需求確認到完成交付，我們把腳本、拍攝、後製與修改節點拆清楚，降低溝通成本。",
    aboutEyebrow: "About Starhorizon",
    aboutPointLabel: "Point of View",
    aboutPointTitle: "我們的製作觀點",
    teamEyebrow: "Team",
    teamTitle: "團隊分工",
    teamDescription: "依專案需求組合企劃、拍攝與後製人員。",
    clientsEyebrow: "Clients",
    clientsTitle: "服務領域",
    quoteEyebrow: "Start A Project",
    quoteTitle: "告訴我們你的影片需求。",
    quoteLead: "表單會收集足夠資訊，讓我們能初步判斷製作範圍、預算與時程。送出後會進入後台詢價管理。",
    quoteSubmitText: "送出詢價",
  },
  partners: [],
  articles: [
    {
      id: "video-production-seo-guide",
      slug: "video-production-seo-guide",
      staticPath: "article-video-production-seo-guide.html",
      title: "品牌影片如何幫助 SEO 與信任建立",
      category: "SEO 觀點",
      publishedAt: "2026-09-03",
      coverUrl: "",
      coverAlt: "品牌影片與搜尋優化文章封面",
      excerpt: "影片不只是社群素材，也能延伸成網站內容、作品案例與搜尋結果能理解的品牌訊號。",
      seoTitle: "品牌影片如何幫助 SEO 與信任建立｜星澔文創",
      seoDescription: "星澔文創分享品牌影片如何透過文章、作品案例與結構化內容，提升搜尋曝光與客戶信任。",
      blocks: [
        { type: "paragraph", text: "當影片只放在社群平台，搜尋引擎能理解的內容其實有限。把影片整理成文章、案例說明與 FAQ，能讓品牌在搜尋結果中更清楚地被看見。" },
        { type: "heading", text: "影片內容要轉成可搜尋的文字" },
        { type: "paragraph", text: "每支影片都可以補上拍攝目的、服務流程、客戶情境、成果摘要與常見問題。這些文字能幫助搜尋引擎判斷頁面主題，也能讓客戶快速知道你是否適合他。" },
        { type: "list", text: "替影片寫清楚主題與服務情境\n補上圖片 alt 文字與文章摘要\n用固定文章網址長期累積搜尋價值" },
      ],
      sort: 1,
      status: "published",
    },
  ],
  workSettings: {
    featuredCategoryIds: ["brand-film", "interview", "podcast", "event"],
    showcaseWorkIds: ["brand-film", "interview", "podcast", "event-recap"],
  },
  workCategories: [
    {
      id: "brand-film",
      title: "品牌形象",
      description: "品牌故事、企業形象、官網主視覺與商業溝通影片。",
      coverMode: "random",
      coverWorkId: "",
      showOnHome: true,
      showOnWorks: true,
      sort: 1,
      status: "published",
    },
    {
      id: "interview",
      title: "人物訪談",
      description: "創辦人、專家、團隊與品牌理念訪談內容。",
      coverMode: "random",
      coverWorkId: "",
      showOnHome: true,
      showOnWorks: true,
      sort: 2,
      status: "published",
    },
    {
      id: "podcast",
      title: "Podcast",
      description: "節目錄影、長片、精華片段與社群延伸內容。",
      coverMode: "random",
      coverWorkId: "",
      showOnHome: true,
      showOnWorks: true,
      sort: 3,
      status: "published",
    },
    {
      id: "event",
      title: "活動紀錄",
      description: "論壇、記者會、展覽、課程與品牌活動精華。",
      coverMode: "random",
      coverWorkId: "",
      showOnHome: true,
      showOnWorks: true,
      sort: 4,
      status: "published",
    },
  ],
  about: {
    title: "我們相信，好的影像不是單純記錄，而是幫品牌完成溝通。",
    body:
      "星澔文創是一間以品牌敘事與商業溝通為核心的影音製作工作室。我們擅長把企業理念、人物觀點、產品特色與活動現場轉化成可被理解、可被分享、可被使用的影像資產。",
    philosophy:
      "每一支影片都應該先回答三件事：誰要看、看完要理解什麼、下一步要做什麼。從這個基礎出發，我們規劃腳本、拍攝節奏、剪輯版本與社群延伸素材。",
    serviceArea: "台灣全區，可依專案需求安排外縣市拍攝。",
    team: [
      {
        name: "製作企劃",
        role: "需求訪談、腳本架構、拍攝規劃",
      },
      {
        name: "影像團隊",
        role: "攝影、燈光、收音、現場執行",
      },
      {
        name: "後製團隊",
        role: "剪輯、調色、字幕、音訊與社群版本輸出",
      },
    ],
    clients: ["品牌形象", "教育課程", "Podcast 節目", "活動紀錄"],
  },
  works: [
    {
      id: "brand-film",
      title: "品牌形象影片",
      category: "品牌形象",
      categoryId: "brand-film",
      client: "精選案例",
      year: "2026",
      coverClass: "g1",
      coverUrl: "",
      videoUrl: "",
      orientation: "landscape",
      summary: "用 90 秒說清楚品牌定位、服務特色與可信任的第一印象。",
      featured: true,
      showcase: true,
      status: "published",
      sort: 1,
    },
    {
      id: "interview",
      title: "人物訪談影片",
      category: "人物訪談",
      categoryId: "interview",
      client: "精選案例",
      year: "2026",
      coverClass: "g2",
      coverUrl: "",
      videoUrl: "",
      orientation: "landscape",
      summary: "把創辦人理念、專家觀點與品牌故事整理成自然有溫度的內容。",
      featured: true,
      showcase: true,
      status: "published",
      sort: 2,
    },
    {
      id: "podcast",
      title: "Podcast 影像節目",
      category: "Podcast",
      categoryId: "podcast",
      client: "精選案例",
      year: "2026",
      coverClass: "g3",
      coverUrl: "",
      videoUrl: "",
      orientation: "landscape",
      summary: "打造節目視覺，延伸成 YouTube 長片與社群短片。",
      featured: true,
      showcase: true,
      status: "published",
      sort: 3,
    },
    {
      id: "event-recap",
      title: "活動紀錄精華",
      category: "活動紀錄",
      categoryId: "event",
      client: "精選案例",
      year: "2026",
      coverClass: "g4",
      coverUrl: "",
      videoUrl: "",
      orientation: "landscape",
      summary: "保留現場氛圍，剪出可宣傳、可回顧的活動精華。",
      featured: true,
      showcase: true,
      status: "published",
      sort: 4,
    },
  ],
  services: [
    {
      id: "brand-film",
      title: "品牌形象影片",
      summary: "企業簡介、品牌故事、形象廣告與官網主視覺影片。",
      target: "適合想建立第一印象、提升專業感與信任感的企業。",
      deliverables: "腳本、拍攝、剪輯、調色、字幕、橫式與直式版本。",
      sort: 1,
      status: "published",
    },
    {
      id: "interview",
      title: "人物訪談影片",
      summary: "創辦人、專家、醫師、老師、團隊故事與品牌理念訪談。",
      target: "適合需要傳遞觀點、專業知識與品牌溫度的團隊。",
      deliverables: "訪綱、拍攝、訪談正片、精華短片、字幕版。",
      sort: 2,
      status: "published",
    },
    {
      id: "podcast",
      title: "Podcast / 節目製作",
      summary: "錄影規劃、拍攝、聲音同步、節目剪輯、片頭片尾與短影音切片。",
      target: "適合想把音訊內容延伸到 YouTube 與社群平台的節目。",
      deliverables: "節目長片、短影音切片、封面、字幕與多比例輸出。",
      sort: 3,
      status: "published",
    },
    {
      id: "social-cuts",
      title: "短影音切片",
      summary: "從長影片整理重點，製作直式短影音、字幕與封面。",
      target: "適合需要穩定經營 Instagram、YouTube Shorts、TikTok 的品牌。",
      deliverables: "直式短片、字幕、標題字卡、封面圖。",
      sort: 4,
      status: "published",
    },
    {
      id: "event",
      title: "活動紀錄",
      summary: "論壇、記者會、展覽、品牌活動與課程精華紀錄。",
      target: "適合需要保留現場內容並做後續宣傳的活動。",
      deliverables: "活動精華、花絮短片、照片或指定格式素材。",
      sort: 5,
      status: "published",
    },
    {
      id: "post-production",
      title: "後期剪輯與包裝",
      summary: "剪輯、調色、字幕、音效、動態字卡與社群版本輸出。",
      target: "適合已有素材，但需要整理成專業影片的品牌。",
      deliverables: "剪輯成片、字幕、調色、音訊整理與多平台輸出。",
      sort: 6,
      status: "published",
    },
  ],
  extendedServices: [
    {
      id: "website",
      title: "品牌網站製作",
      summary: "以清楚的內容架構、品牌視覺與行動路徑，打造能承接影像流量的品牌網站。",
      target: "適合需要建立專業官網、作品網站或服務型落地頁的品牌。",
      deliverables: "網站企劃、視覺設計、響應式頁面、內容上架與基本後台。",
      sort: 1,
      status: "published",
    },
    {
      id: "seo",
      title: "SEO 搜尋優化",
      summary: "整理網站結構、搜尋關鍵字與內容方向，讓有需求的客戶更容易找到品牌。",
      target: "適合希望累積自然搜尋曝光與長期內容效益的企業。",
      deliverables: "基礎健檢、關鍵字規劃、頁面優化、追蹤設定與改善建議。",
      sort: 2,
      status: "published",
    },
  ],
  process: [
    {
      title: "需求諮詢",
      body: "確認影片目的、平台、支數、預算、時程與參考風格。",
      sort: 1,
    },
    {
      title: "初步報價",
      body: "依需求提供報價方向、製作範圍與建議執行方式。",
      sort: 2,
    },
    {
      title: "企劃腳本",
      body: "整理訪談方向、影片架構、拍攝風格與分鏡概念。",
      sort: 3,
    },
    {
      title: "拍攝規劃",
      body: "安排場地、時程、器材、人員與拍攝細節。",
      sort: 4,
    },
    {
      title: "現場拍攝",
      body: "執行攝影、燈光、收音、導演引導與素材管理。",
      sort: 5,
    },
    {
      title: "剪輯後製",
      body: "剪輯、調色、字幕、音樂、動態包裝與版本輸出。",
      sort: 6,
    },
    {
      title: "修改確認",
      body: "依雙方約定修改次數進行調整，確認最終內容。",
      sort: 7,
    },
    {
      title: "完成交付",
      body: "交付橫式、直式、社群版或指定格式檔案。",
      sort: 8,
    },
  ],
};
